"""privacy_foundation"""

import sqlalchemy as sa
from alembic import op

revision = "004_privacy"
down_revision = "003_jobs"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_documents",
        sa.Column("document_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('study','recording','ai_processing','private_panel','recontact')",
            name="ck_document_purpose",
        ),
        sa.CheckConstraint(
            "char_length(body) BETWEEN 1 AND 20000 AND char_length(digest) = 64",
            name="ck_document_body",
        ),
        sa.CheckConstraint("version > 0", name="ck_document_version"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "document_key", "version", "locale", name="uq_document_version"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_document_scope"),
    )
    op.create_index(
        op.f("ix_consent_documents_workspace_id"),
        "consent_documents",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "privacy_requests",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('access','withdrawal','erasure')", name="ck_privacy_kind"),
        sa.CheckConstraint(
            "state IN ('requested','processing','completed')", name="ck_privacy_state"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "subject_id", "request_key", name="uq_privacy_request"),
    )
    op.create_index(
        op.f("ix_privacy_requests_subject_id"), "privacy_requests", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_privacy_requests_workspace_id"), "privacy_requests", ["workspace_id"], unique=False
    )
    op.create_table(
        "privacy_restrictions",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "subject_id", name="uq_privacy_subject"),
    )
    op.create_index(
        op.f("ix_privacy_restrictions_workspace_id"),
        "privacy_restrictions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "retention_policies",
        sa.Column("policy_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("raw_days", sa.Integer(), nullable=False),
        sa.Column("media_days", sa.Integer(), nullable=False),
        sa.Column("derived_days", sa.Integer(), nullable=False),
        sa.Column("export_days", sa.Integer(), nullable=False),
        sa.Column("legal_basis", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version > 0 AND raw_days BETWEEN 1 AND 3650 AND media_days BETWEEN 1 AND 3650 AND derived_days BETWEEN 1 AND 3650 AND export_days BETWEEN 1 AND 3650",
            name="ck_retention_limits",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_retention_scope"),
        sa.UniqueConstraint("workspace_id", "policy_key", "version", name="uq_retention_version"),
    )
    op.create_index(
        op.f("ix_retention_policies_workspace_id"),
        "retention_policies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "assets",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("retention_policy_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=32), nullable=False),
        sa.Column("media_type", sa.String(length=64), nullable=False),
        sa.Column("extension", sa.String(length=8), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('stimulus','attachment','recording')", name="ck_asset_purpose"
        ),
        sa.CheckConstraint(
            "state IN ('pending','uploading','quarantined','ready','blocked','purging','purged')",
            name="ck_asset_state",
        ),
        sa.CheckConstraint(
            "(width IS NULL OR width BETWEEN 1 AND 4096) AND (height IS NULL OR height BETWEEN 1 AND 4096)",
            name="ck_asset_dimensions",
        ),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 16777216 AND char_length(checksum) = 64",
            name="ck_asset_size",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "retention_policy_id"],
            ["retention_policies.workspace_id", "retention_policies.id"],
            name="fk_asset_retention",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key", name="uq_asset_storage"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_asset_scope"),
    )
    op.create_check_constraint(
        "ck_asset_keys", "assets", "storage_key ~ '^[0-9a-f]{32}$' AND checksum ~ '^[0-9a-f]{64}$'"
    )
    op.create_check_constraint(
        "ck_asset_format",
        "assets",
        "(media_type = 'image/png' AND extension = 'png') OR (media_type = 'text/csv' AND extension = 'csv') OR (media_type = 'text/plain' AND extension = 'txt') OR (media_type = 'audio/wav' AND extension = 'wav' AND purpose = 'recording')",
    )
    op.create_foreign_key(
        "fk_asset_owner_scope",
        "assets",
        "memberships",
        ["workspace_id", "owner_id"],
        ["workspace_id", "user_id"],
    )
    op.create_index(op.f("ix_assets_owner_id"), "assets", ["owner_id"], unique=False)
    op.create_index(op.f("ix_assets_retention_until"), "assets", ["retention_until"], unique=False)
    op.create_index(op.f("ix_assets_workspace_id"), "assets", ["workspace_id"], unique=False)
    op.create_table(
        "consent_receipts",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_key", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("presented_digest", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('granted','declined','withdrawn')", name="ck_receipt_decision"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "document_id"],
            ["consent_documents.workspace_id", "consent_documents.id"],
            name="fk_receipt_document",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "subject_id", "receipt_key", name="uq_receipt_key"),
    )
    op.create_index(
        op.f("ix_consent_receipts_subject_id"), "consent_receipts", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_consent_receipts_workspace_id"), "consent_receipts", ["workspace_id"], unique=False
    )
    op.create_table(
        "asset_links",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('stimulus','attachment','recording')", name="ck_link_purpose"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "asset_id"], ["assets.workspace_id", "assets.id"], name="fk_link_asset"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "owner_membership_id"],
            ["memberships.workspace_id", "memberships.id"],
            name="fk_link_member",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id",
            "asset_id",
            "owner_membership_id",
            "purpose",
            name="uq_asset_member_link",
        ),
    )
    op.create_index(
        op.f("ix_asset_links_workspace_id"), "asset_links", ["workspace_id"], unique=False
    )
    op.create_table(
        "upload_intents",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("uploader_id", sa.Uuid(), nullable=False),
        sa.Column("upload_key", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "asset_id"],
            ["assets.workspace_id", "assets.id"],
            name="fk_upload_asset",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", name="uq_upload_asset"),
        sa.UniqueConstraint("workspace_id", "uploader_id", "upload_key", name="uq_upload_key"),
    )
    op.create_index(
        op.f("ix_upload_intents_workspace_id"), "upload_intents", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###

    op.execute("""
        CREATE FUNCTION privacy_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'immutable record';
        END $$;
        CREATE TRIGGER consent_document_immutable BEFORE UPDATE ON consent_documents
            FOR EACH ROW EXECUTE FUNCTION privacy_immutable();
        CREATE TRIGGER retention_policy_immutable BEFORE UPDATE ON retention_policies
            FOR EACH ROW EXECUTE FUNCTION privacy_immutable();
        CREATE TRIGGER consent_receipt_immutable BEFORE UPDATE ON consent_receipts
            FOR EACH ROW EXECUTE FUNCTION privacy_immutable();
        CREATE FUNCTION receipt_digest_check() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM consent_documents WHERE id = NEW.document_id
                AND workspace_id = NEW.workspace_id AND digest = NEW.presented_digest) THEN
                RAISE EXCEPTION 'consent digest mismatch';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER receipt_digest BEFORE INSERT ON consent_receipts
            FOR EACH ROW EXECUTE FUNCTION receipt_digest_check();
        CREATE FUNCTION asset_content_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF (NEW.workspace_id, NEW.owner_id, NEW.storage_key, NEW.checksum, NEW.size_bytes,
                NEW.media_type, NEW.extension, NEW.purpose, NEW.retention_policy_id, NEW.retention_until)
                IS DISTINCT FROM
                (OLD.workspace_id, OLD.owner_id, OLD.storage_key, OLD.checksum, OLD.size_bytes,
                OLD.media_type, OLD.extension, OLD.purpose, OLD.retention_policy_id, OLD.retention_until) THEN
                RAISE EXCEPTION 'immutable asset content';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER asset_content_frozen BEFORE UPDATE ON assets
            FOR EACH ROW EXECUTE FUNCTION asset_content_immutable();
    """)


def downgrade():
    op.execute(
        "DROP TRIGGER asset_content_frozen ON assets; DROP FUNCTION asset_content_immutable();"
    )
    op.execute(
        "DROP TRIGGER receipt_digest ON consent_receipts; DROP FUNCTION receipt_digest_check();"
    )
    op.execute(
        "DROP TRIGGER consent_document_immutable ON consent_documents; DROP TRIGGER retention_policy_immutable ON retention_policies; DROP TRIGGER consent_receipt_immutable ON consent_receipts; DROP FUNCTION privacy_immutable();"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upload_intents_workspace_id"), table_name="upload_intents")
    op.drop_table("upload_intents")
    op.drop_index(op.f("ix_asset_links_workspace_id"), table_name="asset_links")
    op.drop_table("asset_links")
    op.drop_index(op.f("ix_consent_receipts_workspace_id"), table_name="consent_receipts")
    op.drop_index(op.f("ix_consent_receipts_subject_id"), table_name="consent_receipts")
    op.drop_table("consent_receipts")
    op.drop_index(op.f("ix_assets_workspace_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_retention_until"), table_name="assets")
    op.drop_index(op.f("ix_assets_owner_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_retention_policies_workspace_id"), table_name="retention_policies")
    op.drop_table("retention_policies")
    op.drop_index(op.f("ix_privacy_restrictions_workspace_id"), table_name="privacy_restrictions")
    op.drop_table("privacy_restrictions")
    op.drop_index(op.f("ix_privacy_requests_workspace_id"), table_name="privacy_requests")
    op.drop_index(op.f("ix_privacy_requests_subject_id"), table_name="privacy_requests")
    op.drop_table("privacy_requests")
    op.drop_index(op.f("ix_consent_documents_workspace_id"), table_name="consent_documents")
    op.drop_table("consent_documents")
    # ### end Alembic commands ###
