"""versioned_studies"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "005_studies"
down_revision = "004_privacy"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "studies",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=False),
        sa.Column("retention_policy_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("ai_policy", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ai_policy IN ('human_only','assisted')", name="ck_study_ai_policy"),
        sa.CheckConstraint(
            "status IN ('draft','ready','paused','closed','archived')", name="ck_study_status"
        ),
        sa.CheckConstraint("char_length(title) BETWEEN 1 AND 200", name="ck_study_title"),
        sa.ForeignKeyConstraint(
            ["workspace_id", "owner_membership_id"],
            ["memberships.workspace_id", "memberships.id"],
            name="fk_study_owner",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "retention_policy_id"],
            ["retention_policies.workspace_id", "retention_policies.id"],
            name="fk_study_retention",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_study_scope"),
    )
    op.create_index(op.f("ix_studies_workspace_id"), "studies", ["workspace_id"], unique=False)
    op.create_table(
        "study_grants",
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            'jsonb_typeof(capabilities) = \'array\' AND capabilities <@ \'["read","edit","publish","preview","raw","export","ai","review"]\'::jsonb',
            name="ck_grant_capabilities",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "membership_id"],
            ["memberships.workspace_id", "memberships.id"],
            name="fk_grant_member",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "study_id"],
            ["studies.workspace_id", "studies.id"],
            name="fk_grant_study",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "study_id", "membership_id", name="uq_study_grant"),
    )
    op.create_index(
        op.f("ix_study_grants_workspace_id"), "study_grants", ["workspace_id"], unique=False
    )
    op.create_table(
        "study_versions",
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("blocks_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("locales", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consent_documents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'draft' AND published_at IS NULL AND content_hash IS NULL) OR (state = 'published' AND published_at IS NOT NULL AND char_length(content_hash) = 64)",
            name="ck_version_publication",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(blocks_json) = 'array' AND jsonb_array_length(blocks_json) <= 100 AND jsonb_typeof(rules_json) = 'object' AND jsonb_typeof(locales) = 'array' AND jsonb_typeof(consent_documents) = 'object'",
            name="ck_version_json",
        ),
        sa.CheckConstraint(
            "state IN ('draft','published') AND revision > 0 AND number > 0",
            name="ck_version_state",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "study_id"],
            ["studies.workspace_id", "studies.id"],
            name="fk_version_study",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_version_scope"),
        sa.UniqueConstraint("workspace_id", "study_id", "number", name="uq_study_version"),
    )
    op.create_index(
        op.f("ix_study_versions_workspace_id"), "study_versions", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_one_study_draft",
        "study_versions",
        ["study_id"],
        unique=True,
        postgresql_where=sa.text("state = 'draft'"),
    )
    op.create_table(
        "launches",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state IN ('ready','paused','closed')", name="ck_launch_state"),
        sa.ForeignKeyConstraint(
            ["workspace_id", "version_id"],
            ["study_versions.workspace_id", "study_versions.id"],
            name="fk_launch_version",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "version_id", name="uq_launch_version"),
    )
    op.create_index(op.f("ix_launches_workspace_id"), "launches", ["workspace_id"], unique=False)
    # ### end Alembic commands ###

    op.add_column("consent_receipts", sa.Column("study_version_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_receipt_study_version",
        "consent_receipts",
        "study_versions",
        ["workspace_id", "study_version_id"],
        ["workspace_id", "id"],
    )
    op.execute("""
        CREATE FUNCTION study_consent_scope() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE doc consent_documents%ROWTYPE;
        BEGIN
            SELECT * INTO doc FROM consent_documents WHERE id = NEW.document_id;
            IF doc.purpose = 'study' THEN
                IF NOT EXISTS (SELECT 1 FROM study_versions WHERE id = NEW.study_version_id
                    AND workspace_id = NEW.workspace_id AND state = 'published'
                    AND consent_documents ->> doc.locale = doc.id::text) THEN
                    RAISE EXCEPTION 'study consent version mismatch';
                END IF;
            ELSIF NEW.study_version_id IS NOT NULL THEN
                RAISE EXCEPTION 'consent scope mismatch';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER receipt_study_scope BEFORE INSERT ON consent_receipts
            FOR EACH ROW EXECUTE FUNCTION study_consent_scope();
        CREATE FUNCTION study_version_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' AND EXISTS (
                SELECT 1 FROM studies s JOIN memberships m ON m.id = s.owner_membership_id
                JOIN privacy_restrictions p ON p.workspace_id = s.workspace_id AND p.subject_id = m.user_id
                WHERE s.id = OLD.study_id
            ) THEN RETURN OLD; END IF;
            IF OLD.state = 'published' THEN RAISE EXCEPTION 'published version is immutable'; END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            IF (NEW.study_id, NEW.workspace_id, NEW.number) IS DISTINCT FROM (OLD.study_id, OLD.workspace_id, OLD.number) THEN
                RAISE EXCEPTION 'version identity is immutable';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER study_version_immutable BEFORE UPDATE OR DELETE ON study_versions
            FOR EACH ROW EXECUTE FUNCTION study_version_frozen();
        CREATE FUNCTION launch_published_check() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'UPDATE' AND (NEW.version_id, NEW.workspace_id) IS DISTINCT FROM (OLD.version_id, OLD.workspace_id) THEN
                RAISE EXCEPTION 'launch version is immutable';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM study_versions WHERE id = NEW.version_id AND workspace_id = NEW.workspace_id AND state = 'published') THEN
                RAISE EXCEPTION 'launch requires published version';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER launch_published BEFORE INSERT OR UPDATE ON launches
            FOR EACH ROW EXECUTE FUNCTION launch_published_check();
        CREATE FUNCTION study_policy_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF (NEW.workspace_id, NEW.owner_membership_id, NEW.retention_policy_id, NEW.ai_policy) IS DISTINCT FROM
                (OLD.workspace_id, OLD.owner_membership_id, OLD.retention_policy_id, OLD.ai_policy) THEN
                RAISE EXCEPTION 'study policy and scope are immutable';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER study_policy_immutable BEFORE UPDATE ON studies
            FOR EACH ROW EXECUTE FUNCTION study_policy_frozen();
    """)


def downgrade():
    op.execute(
        "DROP TRIGGER IF EXISTS receipt_study_scope ON consent_receipts; DROP FUNCTION IF EXISTS study_consent_scope();"
    )
    op.drop_constraint(
        "fk_receipt_study_version", "consent_receipts", type_="foreignkey", if_exists=True
    )
    op.drop_column("consent_receipts", "study_version_id", if_exists=True)
    op.execute(
        "DROP TRIGGER study_policy_immutable ON studies; DROP FUNCTION study_policy_frozen();"
    )
    op.execute("DROP TRIGGER launch_published ON launches; DROP FUNCTION launch_published_check();")
    op.execute(
        "DROP TRIGGER study_version_immutable ON study_versions; DROP FUNCTION study_version_frozen();"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_launches_workspace_id"), table_name="launches")
    op.drop_table("launches")
    op.drop_index(op.f("ix_study_versions_workspace_id"), table_name="study_versions")
    op.drop_table("study_versions")
    op.drop_index(op.f("ix_study_grants_workspace_id"), table_name="study_grants")
    op.drop_table("study_grants")
    op.drop_index(op.f("ix_studies_workspace_id"), table_name="studies")
    op.drop_table("studies")
    # ### end Alembic commands ###
